spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: x
            client-secret: x
            scope:
              - email
              - profile
jwt:
  issuer: user@gmail.com
  secret_key: x