spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: x
            client-secret: x
            scope:
              - email
              - profile
jwt:
  issuer: dev-auth.mj.com
  secret_key: x